insert into audit_questions(question_id,question,audit_type,response) values (1,'Have all Change requests followed SDLC before PROD move?','Internal','')
insert into audit_questions(question_id,question,audit_type,response) values (2,'Have all Change requests been approved by the application owner?','Internal','')
insert into audit_questions(question_id,question,audit_type,response) values (3,'Are all artifacts like CR document, Unit test cases available?','Internal','')
insert into audit_questions(question_id,question,audit_type,response) values (4,'Is the SIT and UAT sign-off available?','Internal','')
insert into audit_questions(question_id,question,audit_type,response) values (5,'Is data deletion from the system done with application owner approval?','Internal','')
insert into audit_questions(question_id,question,audit_type,response) values (6,'Have all Change requests followed SDLC before PROD move?','SOX','')
insert into audit_questions(question_id,question,audit_type,response) values (7,'Have all Change requests been approved by the application owner?','SOX','')
insert into audit_questions(question_id,question,audit_type,response) values (8,'For a major change, was there a database backup taken before and after PROD move?','SOX','')
insert into audit_questions(question_id,question,audit_type,response) values (9,'Has the application owner approval obtained while adding a user to the system?','SOX','')
insert into audit_questions(question_id,question,audit_type,response) values (10,'Is data deletion from the system done with application owner approval?','SOX','')